### ISSUE TITLE
How to train LBM on different building's data

### ISSUE THREAD

**Issue by loneharoon** [MingjunZhong/LatentBayesianMelding#4]
Hi,
While going through the code I found that methods `train` and `train_on_chunk` are not implemented in `latent_Bayesian_melding.py`. and currently, you use JSON file to get the model parameters and run the LBM. I was wondering how to get model parameters for buildings which have

1. Different data sampling rate (since current parameters have been obtained on data of 2 minutes rate)
2. Have appliances which are not in JSON file say Air-conditioner

**Comment by MingjunZhong** [comment]
1. If your data has different sampling rate to mine in the JSON file, there are two things you need to look at: a) for the summary statistics parameters, e.g., total energy, duration of appliance usage, and number of cycles, you probably still can use them in my JSON file because sampling rate would not change them; b) for the HMM parameters, they are affected by the sampling rates, and so you need to learn these parameters.
2. For the appliances which are not in JSON file, you have to extract these parameters yourself.

**Comment by loneharoon** [comment]
Thanks, Mingjun for the prompt reply. I have few other queries corresponding to each of your points. Please correct me if I am wrong.

1. For each appliance, you have 9 model parameters. First 3 (mean, startprob and tranprob) are HMM parameters and remaining 6 are statistical parameters. So you mean that for different sampling rates I need to get only HMM parameters and statistical parameters can be taken from JSON file as such?
2. How can I extract these parameters? It would be really great If you can point me to some source implementation, If any exists.

**Comment by MingjunZhong** [comment]
1. Basically, you need to think about if sampling rate affects them. Yes you only need to get HMM parameters. But for the summary statistics parameters, you need to check the units as well - if you use that JSON file, you need to transfer the units to yours.
2. For the HMM parameters, I think there are publically available packages because HMMs are used very often. I am afraid for summary statistics, you have to write your codes. It won't be hard for all these parameters: all you need to do is to translate the signals to appliance states, and then these parameters can be easily extracted.

**Comment by loneharoon** [comment]
Thanks, I will give it a try. Is there a documentation of mentioned statistical parameters, i.e., what do they mean and how are they computed?

**Comment by MingjunZhong** [comment]
Would it be helpful you read section 5.2 in my paper? Indeed I need to write an extended paper to demonstrate all these issues.

**Comment by loneharoon** [comment]
Sure. Thanks a lot for prompt replies.
